version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Exporting environment variables...
      - printenv > .env
      - echo Cleaning up S3 bucket...
      - aws s3 rm s3://itchson.eth --recursive
  build:
    commands:
      - echo Exporting Next.js project...
      - npm run export
      - echo Current Working Directory is...
      - pwd  # Debugging line to print current directory
      - echo Listing contents of out directory...
      - ls -al out  # Debugging line
  post_build:
    commands:
      - echo Build complete...

artifacts:
  files: '**/*'
  base-directory: 'out'

env:
  variables:
    CI: 'true'
