version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Exporting environment variables...
      - printenv > .env

  build:
    commands:
      - echo Building the Next.js app...
      - npm run export

  post_build:
    commands:
      - echo Build complete...

artifacts:
  files: '**/*'
  base-directory: 'out/'

env:
  variables:
    CI: 'true'
