version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install -g next
  pre_build:
    commands:
      - echo Exporting environment variables...
      - printenv > .env
  build:
    commands:
      - echo Compiling the Node.js code...
      - npm run build
  post_build:
    commands:
      - echo Build complete...

artifacts:
  files: -'**/*'
  base-directory: 'build'

env:
  variables:
    CI: 'true'
