version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Exporting environment variables...
      - printenv > .env
      - echo Cleaning up S3 bucket...
      - aws s3 rm s3://itchson.eth --recursive
  build:
    commands:
      - echo Exporting Next.js project...
      - npm run export
  post_build:
    commands:
      - echo Build complete...
      
artifacts:
  files: 'out/**/*'
  base-directory: 'out'

env:
  variables:
    CI: 'true'
