version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
      - npm install -g next
      - npm install gray-matter remark remark-html

  pre_build:
    commands:
      - echo Exporting environment variables...
      - printenv > .env
  
  build:
    commands:
      - echo Compiling the Node.js code...
      - npm run build

  post_build:
    commands:
      - echo Build complete...

artifacts:
  files: '**/*'
  base-directory: '.next/'

env:
  variables:
    CI: 'true'
